### ISSUE TITLE
Problems with exiting from CLI

### ISSUE THREAD

**Issue by amadeus-8** [SBoudrias/Inquirer.js#1050]
I've created simple CLI using inquirer and child_process. And i have problem, when i'am closing process with CTLR+C, it seems like its still running process, because terminal not responding anything. And i have to close terminal every time and open it again, it's uncomfortable for me. What i need to do, to exit all processes with simple CTRL+C command? Searched so many solutions in google, but no result. Hope somebody can help me with it
```js
const inquirer = require('inquirer')
const { execSync } = require('child_process')
const { readdirSync } = require('fs')

const targetFolder = './src/pages'

const directories = readdirSync(targetFolder)

const questions = [
    {
        type: 'list',
        name: 'page',
        message: 'Choose page to compile',
        choices: directories,
    },
]

inquirer.prompt(questions).then(({ page }) => {
    const options = {
        stdio: 'inherit',
    }
    execSync(`npm run start -- --env page=${page}`, options)
})
```

**Comment by raskyer** [comment]
We have the same issue on Powershell when hitting CTRL+ C: 

```
ExitPromptError: User force closed the prompt with 0 null
    at C:\dev\repos\new-banners\banners\banners\Tools\studio-release-script\node_modules\@inquirer\core\dist\cjs\lib\create-prompt.js:60:28
    at Emitter.emit (C:\dev\repos\new-banners\banners\banners\Tools\studio-release-script\node_modules\signal-exit\dist\cjs\index.js:71:19)
    at #processEmit (C:\dev\repos\new-banners\banners\banners\Tools\studio-release-script\node_modules\signal-exit\dist\cjs\index.js:240:27)
    at #process.emit (C:\dev\repos\new-banners\banners\banners\Tools\studio-release-script\node_modules\signal-exit\dist\cjs\index.js:191:37)
    at process.callbackTrampoline (node:internal/async_hooks:128:17)
```

**Comment by SBoudrias** [comment]
@raskyer is it the same issue? Is the problem the error itself? Or that even with the error the prompt doesn't exit?

**Comment by SBoudrias** [comment]
`process.exit()` force the process to exit.

Without it, Node waits for timeouts and other scheduled async operations to complete in order to safely exit. That's not specific to Inquirer.

**Comment by ccaspanello** [comment]
I too am running into this issue.  While it may or may not be an inquirer issue I'm looking for a clean solution suggested by the Inquirer maintainers.

**Comment by SBoudrias** [comment]
We have a guide for handling errors in the README https://github.com/SBoudrias/Inquirer.js#handling-ctrlc-gracefully

@ccaspanello can you help by providing the version of `@inquirer/prompts` you're using, OS, terminal and Node runtime (like is this with Node or Bun or etc?) Could you also please describe the behaviour you encounter and the behaviour you expect?

**Comment by ccaspanello** [comment]
@SBoudrias  - This is perfect.  I missed it in the readme.  Thank you very much!!!!
