### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by orchoban** [SBoudrias/Inquirer.js#1060]
Hello. I don't know what happened :-(
```
SyntaxError: Unexpected identifier
    at ScreenManager.normalizedCliWidth (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\utils\screen-manager.js:149:19)
    at ScreenManager.render (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\utils\screen-manager.js:81:24)
    at InputPrompt.render (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\prompts\input.js:67:17)
    at InputPrompt._run (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\prompts\input.js:34:10)
    at C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\prompts\base.js:62:12
    at new Promise (<anonymous>)
    at InputPrompt.run (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\prompts\base.js:61:12)
    at C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\inquirer\lib\ui\prompt.js:108:30
    at Observable._subscribe (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\rxjs\dist\cjs\internal\observable\defer.js:8:31)
    at Observable._trySubscribe (C:\Users\OrChu\Desktop\repos\reco\react.cordova\node_modules\rxjs\dist\cjs\internal\Observable.js:41:25)
```
https://github.com/orchoban/react.cordova/blob/master/bin/reco2/init.js#L79
_see it on version 2.4.2-beta.0_

**Comment by LitoMore** [comment]
You could open that file and see what kind of syntax error there is.
