### ISSUE TITLE
SyntaxError: Octal literals are not allowed in strict mode

### ISSUE THREAD

**Issue by kaelzhang** [SBoudrias/Inquirer.js#111]
``` bash
/xxxxx/node_modules/inquirer/lib/utils/tty.js:81
  return this.write("\033[?25l");
                      ^^
SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:69:16)
    at Module._compile (module.js:432:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
```
## How to produce
- env: node.js >= 0.10.7
- alias node='node --use-strict'

I am using node.js 0.11.13 with `--harmony` to have a taste of generator functions and `yield`. To do this, I also have to turn on the `--use-strict` flag. 

``` bash
alias node='node --harmony --use-strict'
```

But in strict mode:

> SCRIPT1039: Octal numeric literals and escape characters not allowed in strict mode

**Comment by Poxiaozhiyu** [comment]
‘033’ change to '0o33'

**Comment by jiandandkl** [comment]
\033 --> \x1b
