### ISSUE TITLE
Inquirer Error in Pnpm workspace

### ISSUE THREAD

**Issue by imohuan** [SBoudrias/Inquirer.js#1123]
`pnpm-workspace.yaml`
``` yaml
packages:
  - "packages/*"
```
`packages.json`
``` json
{
  "private": true,
  "workspaces": ["packages/*"],
  "dependencies": {
    "chalk": "^5.0.1",
    "inquirer": "^8.2.4"
  },
  "devDependencies": {
    "@types/inquirer": "^8.2.1"
  }
}
```
`index.ts`
``` typescript
import inquirer from "inquirer";
console.log("inquirer", inquirer);
(async () => {
  const result = await inquirer.prompt([
    {
      type: "list",
      message: "Please choose a fruit:",
      name: "fruit",
      choices: ["Apple", "Pear", "Banana"],
      filter: function (val) {
        return val.toLowerCase();
      }
    }
  ]);
  console.log("result", result);
})();
```
### The error message
``` txt
TypeError: chalk.blue is not a function
    at Object.<anonymous> (G:\Project\imohuan\node_modules\.pnpm\log-symbols@4.1.0\node_modules\log-symbols\index.js:6:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader (C:\Users\26522\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\registry.npmmirror.com+esbuild-register@3.3.2_esbuild@0.14.22\node_modules\esbuild-register\dist\node.js:2262:9)
    at Object.extensions..js (C:\Users\26522\AppData\Roaming\npm\pnpm-global\5\node_modules\.pnpm\registry.npmmirror.com+esbuild-register@3.3.2_esbuild@0.14.22\node_modules\esbuild-register\dist\node.js:4801:24)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (G:\Project\imohuan\node_modules\.pnpm\ora@5.4.1\node_modules\ora\index.js:6:20)
```

**Comment by imohuan** [comment]
`package.json`
### Chalk reported that the error was resolved
``` json
{
  "peerDependencies": {
    "chalk": "^4.1.2"
   },
}
```

### run `esno index.ts`
```
 stripAnsi is not function
```

`node_modules\.pnpm\string-width@4.2.3\node_modules\string-width\index.js`
```  typescript
'use strict';
const stripAnsi = require('strip-ansi');
const isFullwidthCodePoint = require('is-fullwidth-code-point');
const emojiRegex = require('emoji-regex');

const stringWidth = string => {
	if (typeof string !== 'string' || string.length === 0) {
		return 0;
	}

        // There are two positions. This is just one
	// string = stripAnsi(string);    // old code
	string = stripAnsi.default(string);  // new code  -->  stripAnsi: { default: () => {} }, 

	if (string.length === 0) {
		return 0;
	}
       //.....
```
