### ISSUE TITLE
[Bug] TypeError: Cannot call a class constructor without |new|

### ISSUE THREAD

**Issue by nandin-borjigin** [SBoudrias/Inquirer.js#1305]
```
120 | 
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 | 
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
      at run (<project_dir>/node_modules/@inquirer/core/dist/esm/lib/hook-engine.mjs:87:13)
      at workLoop (<project_dir>/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:77:24)
      at <project_dir>/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:86:20
```

Environment:
- Mac Studio (Apple M1 Max) 
- macOS 13.5.2 (22G91)
- bun 1.0.2 (not Node.js)
- @inquirer/checkbox 1.3.11 (1.3.8 works without problem)

Introduced by https://github.com/SBoudrias/Inquirer.js/commit/8a39c69b3acbe26a774993b2a8538e343fff8b72

Culprit: `withUpdates` return a bound version of `AsyncResource` constructor but it is called without `new` 

https://github.com/SBoudrias/Inquirer.js/blob/3a9adcfedbd302959f1cd37f7de969eead6fa410/packages/core/src/lib/hook-engine.mts#L120-L124

**Comment by nandin-borjigin** [comment]
It's rather a bun issue

https://github.com/oven-sh/bun/issues/4787
