### ISSUE TITLE
class constructor error

### ISSUE THREAD

**Issue by christoph88** [SBoudrias/Inquirer.js#1310]
I get following error when trying to run this:

```
const answer = async () => {
  return await input({ message: "Enter your name" });
};

console.log(answer());
```
cmd
```
bun run start
$ bun run index.ts --help
Promise { <pending> }
? Enter your name
120 | 
121 | class AsyncResource {
122 |   type;
123 |   #snapshot;
124 | 
125 |   constructor(type, options) {
                             ^
TypeError: Cannot call a class constructor without |new|
      at AsyncResource (node:async_hooks:125:26)
      at run (/Users/christoph/Code/digital/digital-ai-control-mendable/node_modules/@inquirer/core/dist/esm/lib/hook-engine.mjs:87:13)
      at workLoop (/Users/christoph/Code/digital/digital-ai-control-mendable/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:76:24)
      at /Users/christoph/Code/digital/digital-ai-control-mendable/node_modules/@inquirer/core/dist/esm/lib/create-prompt.mjs:85:20
error: script "start" exited with code 1 (SIGHUP)
```

**Comment by SBoudrias** [comment]
This is a bun bug. You can report it over there.

**Comment by christoph88** [comment]
I have the same issue in node

**Comment by christoph88** [comment]
@SBoudrias the issue is in your side https://github.com/oven-sh/bun/issues/5997

**Comment by Jarred-Sumner** [comment]
Confirming that this is a bug in Bun. We are missing the `bind` function in `AsyncResource`.
