### ISSUE TITLE
list prompts break when default is not one of the list choices.

### ISSUE THREAD

**Issue by dnozay** [SBoudrias/Inquirer.js#203]
Tried to use a generator with all the default options.

It failed with:
```
/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9379
        throw e;
              ^
TypeError: Cannot read property 'name' of undefined
    at Prompt.render (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/lib/prompts/list.js:99:69)
    at Prompt.onSubmit (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/lib/prompts/list.js:127:16)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1950:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1882:35)
    at AutoDetachObserverPrototype.next (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:9376:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Volumes/ramdisk/jk/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1882:35)
    at AnonymousObserver._onNext (/Volumes/ramdisk/jk/lib/no
```

Here is the code for the list prompts:
```
  // Render choices or answer depending on the state
  if ( this.status === "answered" ) {
    message += chalk.cyan( this.opt.choices.getChoice(this.selected).name ) + "\n";
  } else {
    message += choicesStr;
  }
```

and here is the code from the generator.
```

Generator.prototype.askForTemplates = function askForTemplates() {
  var cb = this.async();
  var prompts = [{
    name: 'templateType',
    type: 'list',
    message: 'Site template',
    choices: ['Default Jekyll', 'HTML5 ★ Boilerplate'],
    default: 'default'
  },
  {
    name: 'h5bpCss',
    type: 'confirm',
    message: 'Add H5★BP CSS files?',
    when: function (answers) {
      return answers.templateType === 'HTML5 ★ Boilerplate';
    }
  }
  // ... etc
  }];

  console.log(chalk.yellow('\nChoose a template.') + ' ☛');

  this.prompt(prompts, function (props) {

    setPromptDefaults(prompts, props);
    this.h5bpCss       = props.h5bpCss;
    this.templateType  = props.templateType;

    if (props.templateType === 'Default Jekyll') {
      this.templateType = 'default';
    }
    else if (props.templateType === 'HTML5 ★ Boilerplate') {
      this.templateType = 'h5bp';
    }

    cb();
  }.bind(this));
};
```

**Comment by dnozay** [comment]
as you can see if `default` is not one of the `choices` it breaks at runtime; it's fine to close this as "not a bug" but maybe we can make that part fool-proof.

**Comment by mrkmg** [comment]
This no longer appears to be a bug.
