### ISSUE TITLE
node debug issues

### ISSUE THREAD

**Issue by knownasilya** [SBoudrias/Inquirer.js#207]
Here's the error, when trying to hit 'Enter' on an option after `node debug index.js`.

```
node debug index.js
< debugger listening on port 5858
connecting... ok
break in index.js:1
  1 'use strict';
  2
  3 var spawn = require('child_process').spawn;
debug> c
debug> ? Select a package.json script command to run, e.g. npm run [command]. (Use arrow keys)
  test
  install
❯ start

< /Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8741
<                 throw e;
<                       ^

< TypeError: Object #<Socket> has no method 'getWindowSize'
<     at Prompt.tty.clean (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/lib/utils/tty.js:23:57)
<     at Prompt.onSubmit (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/lib/prompts/list.js:122:8)
<     at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1852:12)
<     at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1781:22)
<     at AutoDetachObserverPrototype.next (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8738:31)
<     at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1781:22)
<     at AnonymousObserver.observableProto.take [as _onNext] (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:3988:30)
<     at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1852:12)
<     at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1781:22)
<     at AutoDetachObserverPrototype.next (/Users/iradchenko/sandbox/run-scripts/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8738:31)
```

**Comment by SBoudrias** [comment]
This is the commit causing your issue: https://github.com/SBoudrias/Inquirer.js/commit/9abf288afb06a7133f1eddeb61eddb7f983fba1a

Feel free to send a PR fixing it. Basically copying this logic in an internal helper or an external package: https://github.com/medikoo/cli-color/blob/master/index.js#L98

**Comment by SBoudrias** [comment]
FYI I unpublished inquirer 0.8.1

To fix further issue for now:

```js
npm install inquirer@0.8.0
```
