### ISSUE TITLE
Error: ENXIO, no such device or address '/dev/tty'

### ISSUE THREAD

**Issue by gdbtek** [SBoudrias/Inquirer.js#211]
I got following errors when I build my project, which use `Inquirer.js`, under Jenkins Ubuntu x64. However, I don't get this errors when I SSH to the box and run from ssh console. Any thought? 

```
11:16:43 fs.js:439
11:16:43   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
11:16:43                  ^
11:16:43 Error: ENXIO, no such device or address '/dev/tty'
11:16:43     at Object.fs.openSync (fs.js:439:18)
11:16:43     at Object.<anonymous> (/opt/jenkins/workspace/utilities/create-stacks/node_modules/inquirer/node_modules/ttys/index.js:9:18)
11:16:43     at Module._compile (module.js:456:26)
11:16:43     at Object.Module._extensions..js (module.js:474:10)
11:16:43     at Module.load (module.js:356:32)
11:16:43     at Function.Module._load (module.js:312:12)
11:16:43     at Module.require (module.js:364:17)
11:16:43     at require (module.js:380:17)
11:16:43     at Object.<anonymous> (/opt/jenkins/workspace/utilities/create-stacks/node_modules/inquirer/lib/ui/baseUI.js:8:12)
11:16:43     at Module._compile (module.js:456:26)
```

**Comment by SBoudrias** [comment]
Update your inquirer version, we unpublished the version using ttys for failures it could cause in CI.

**Comment by gdbtek** [comment]
@SBoudrias  so I should use https://github.com/SBoudrias/Inquirer.js/releases/tag/v0.8.0 instead of `v0.8.1`, am I correct? Thanks

**Comment by gdbtek** [comment]
use `v0.8.0` and now I don't have the issue. Thanks
