### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by ArvoGuo** [SBoudrias/Inquirer.js#237]
```
var inquirer = require("inquirer");
inquirer.prompt(["what is you name"], function( answers ) {
    console.log(answers)
});
```

```
➜  test  node test.inquirer.js 



/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: undefined is not a function
    at PromptUI.fetchAnswer (/Users/Arvo/github/test/node_modules/inquirer/lib/ui/prompt.js:92:16)
    at MapObserver.selector (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:4383:20)
    at MapObserver.tryCatcher (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at MapObserver.onNext (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:4591:42)
    at MapObserver.tryCatcher (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:5018:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:1894:35)
    at InnerObserver.onNext (/Users/Arvo/github/test/node_modules/inquirer/node_modules/rx/dist/rx.js:3329:91)
    at InnerObserver.tryCatcher (/Us%     
```

**Comment by SBoudrias** [comment]
`inquirer.prompt` take an array of question objects. Please read the documentation.
