### ISSUE TITLE
Can't run inquirer in a spawned process

### ISSUE THREAD

**Issue by jviotti** [SBoudrias/Inquirer.js#269]
Take the following simple inquirer script:

```js
var inquirer = require('inquirer')

inquirer.prompt([ {
  type: 'input',
  name: 'name',
  message: 'What\'s your name?'
} ], function(answers) {
  console.log(answers.name)
})
```

And another script that tries to run the above script with `child_process.spawn`:

```js
var child_process = require('child_process')

var script = child_process.spawn('node', [ './script.js' ])

script.stderr.on('data', function(data) {
  console.log(data.toString())
})

script.on('end', function() {
  console.log('Done')
})
```

The following error is printed to `stderr`:

```
/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:549
    throw e;
          ^
TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/node_modules/readline2/index.js:55:51)
    at ScreenManager.render (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/utils/screen-manager.js:19:27)
    at Prompt.render (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/prompts/input.js:75:15)
    at Prompt._run (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/prompts/input.js:49:8)
    at Prompt.run (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/ui/prompt.js:83:12)
    at module.exports (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at /Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/lib/utils/utils.js:16:7
    at tryCatcher (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at setDisposable (/Users/jviotti/Projects/personal/inquirerspawn/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5380:36)
```

Error location: https://github.com/SBoudrias/readline2/blob/master/index.js#L51.

**Comment by SBoudrias** [comment]
Your subprocess is not a TTY, so it cannot run inquirer.

It'll work if you inherit the stdio. https://nodejs.org/api/child_process.html#child_process_options_stdio

**Comment by matthewp** [comment]
@SBoudrias There is no such option for child_process.exec it seems, do you know if that's right? I think you must use spawn when creating a child using inquirer.

**Comment by SBoudrias** [comment]
It is possible you can only use spawn. The important thing is that you need to be able to inherit the stdio.

**Comment by thewebartisan7** [comment]
This just make the trick:

require(`./scripts/my-inquirer-script.js`);
