### ISSUE TITLE
Not working under alpine linux in docker

### ISSUE THREAD

**Issue by lfilho** [SBoudrias/Inquirer.js#312]
I'm trying to wrap an app that uses Inquirer.js in a Docker container, using Alpine Linux (bash) but it returns the error:

```
/usr/lib/node_modules/freetime-cli/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:549
    throw e;
    ^

TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/node_modules/readline2/index.js:55:51)
    at ScreenManager.render (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/utils/screen-manager.js:19:27)
    at Prompt.render (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/prompts/input.js:75:15)
    at Prompt._run (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/prompts/input.js:49:8)
    at Prompt.run (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/ui/prompt.js:83:12)
    at module.exports (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at /usr/lib/node_modules/freetime-cli/node_modules/inquirer/lib/utils/utils.js:16:7
    at tryCatcher (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:537:29)
    at setDisposable (/usr/lib/node_modules/freetime-cli/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:5380:36)
```

Versions:
```
Inquirer.js 0.9.0
GNU bash, version 4.3.42(1)-release (x86_64-alpine-linux-musl)
Node v4.2.3
```

**Comment by lfilho** [comment]
Sorry, my bad. I forgot to pass `-t` to docker in order to emulate a real tty. Now it worked. Sorry for that
