### ISSUE TITLE
type list, hangs with undefined values

### ISSUE THREAD

**Issue by mh-cbon** [SBoudrias/Inquirer.js#364]
hi,

this snippet will hang, because of an `undefined` value within the array of values.

```js
var opts = browser.services.filter(filterServices).map(function (s){return s.txt.name;})
opts.push("search more...");
opts.push(undefined);
inquirer.prompt([{message: 'Choose a friend', choices: opts, name:'res', type:'list'}])
.then(function (answers) {
    var selected = answers.res;
    if (selected.match(/^search more[\.]{3}$/)) then(false)
     else then(selected)
}).catch(next);
```

```sh
TypeError: Cannot read property 'type' of undefined
    at /home/mh-cbon/projects/bonjour-chat/node_modules/inquirer/lib/objects/choices.js:16:12
    at Array.map (native)
    at new module.exports (/home/mh-cbon/projects/bonjour-chat/node_modules/inquirer/lib/objects/choices.js:15:26)
    at Prompt.module.exports (/home/mh-cbon/projects/bonjour-chat/node_modules/inquirer/lib/prompts/base.js:43:24)
    at new Prompt (/home/mh-cbon/projects/bonjour-chat/node_modules/inquirer/lib/prompts/list.js:25:8)
    at PromptUI.fetchAnswer (/home/mh-cbon/projects/bonjour-chat/node_modules/inquirer/lib/ui/prompt.js:77:16)
    at tryCatcher (/home/mh-cbon/projects/bonjour-chat/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/home/mh-cbon/projects/bonjour-chat/node_modules/rx/dist/rx.js:2140:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/mh-cbon/projects/bonjour-chat/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/home/mh-cbon/projects/bonjour-chat/node_modules/rx/dist/rx.js:63:31)
```

**Comment by SBoudrias** [comment]
Don't you think it's normal to fail on a type error?

**Comment by mh-cbon** [comment]
If that is the way you prefer to handle undefined / null / boolean / meaningless values.
That's all fine.
