### ISSUE TITLE
Global Install

### ISSUE THREAD

**Issue by Starli0n** [SBoudrias/Inquirer.js#397]
Hi,

I tried to figure out how to install inquirer globally.
I did this:
````
npm install -g inquirer
> spawn-sync@1.0.15 postinstall C:\Users\Starli0n\AppData\Roaming\npm\node_modules\inquirer\node_modules\spawn-sync

> node postinstall

C:\Users\Starli0n\AppData\Roaming\npm
`-- inquirer@1.1.2
  +-- ansi-escapes@1.4.0
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | `-- supports-color@2.0.0
  +-- cli-cursor@1.0.2
  | `-- restore-cursor@1.0.1
  |   +-- exit-hook@1.1.1
  |   `-- onetime@1.1.0
  +-- cli-width@2.1.0
  +-- external-editor@1.0.3
  | +-- extend@3.0.0
  | +-- spawn-sync@1.0.15
  | | +-- concat-stream@1.5.1
  | | | +-- inherits@2.0.1
  | | | +-- readable-stream@2.0.6
  | | | | +-- core-util-is@1.0.2
  | | | | +-- isarray@1.0.0
  | | | | +-- process-nextick-args@1.0.7
  | | | | +-- string_decoder@0.10.31
  | | | | `-- util-deprecate@1.0.2
  | | | `-- typedarray@0.0.6
  | | `-- os-shim@0.1.3
  | `-- temp@0.8.3
  |   +-- os-tmpdir@1.0.1
  |   `-- rimraf@2.2.8
  +-- figures@1.7.0
  | `-- object-assign@4.1.0
  +-- lodash@4.13.1
  +-- mute-stream@0.0.6
  +-- pinkie-promise@2.0.1
  | `-- pinkie@2.0.4
  +-- run-async@2.2.0
  | `-- is-promise@2.1.0
  +-- rx@4.1.0
  +-- string-width@1.0.1
  | +-- code-point-at@1.0.0
  | | `-- number-is-nan@1.0.0
  | `-- is-fullwidth-code-point@1.0.0
  +-- strip-ansi@3.0.1
  | `-- ansi-regex@2.0.0
  `-- through@2.3.8

````

And then I created a file `hello.js` like in the documentation
````javascript
var inquirer = require('inquirer');
inquirer.prompt([/* Pass your questions in here */]).then(function (answers) {
    // Use user feedback for... whatever!!
});
````

And trying to launch it using, I had this error:

````
node hello.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Tools\System\Hello.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
````

I checked that `C:\Users\Starli0n\AppData\Roaming\npm` is on my PATH environment variable.

Could you help me on that ?

**Comment by SBoudrias** [comment]
Node doesn't load global packages.

**Comment by Starli0n** [comment]
I found a walkaround by setting the `NODE_PATH` environment variable to make it possible.

http://stackoverflow.com/a/15646750
