### ISSUE TITLE
Rx example, bug in documentation?

### ISSUE THREAD

**Issue by AeonRush** [SBoudrias/Inquirer.js#437]
Hi
I have 
` "rx": "^4.1.0"`
when I tried to run this [code](https://gist.github.com/justin-calleja/833718609ba78143a939#file-pizza-js), I had an error

```javascript
inquirer.prompt(prompts).process.subscribe(
                                ^

TypeError: Cannot read property 'subscribe' of undefined
    at Object.<anonymous> (D:\Workplace\deploy\config\test.js:29:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

When I tried inquirer.prompt(prompts).ui.process it's worked, but, `onComplete` event doesn't get `answers`, `console.log(arguments)` returns to me `{}`

Seems we need documentation for this feature.

**Comment by ev1stensberg** [comment]
Hi! Please check out the new examples, they're more consistent. Also, the API has changed, but the new examples should work 👍

**Comment by ev1stensberg** [comment]
```js
inquirer.prompt(prompts).ui.process.subscribe(
  function(answer) {
  // answers go here
  },
  function(err) {
  // catch errors
  },
  function() {
  // on completed, this is where you could hook up additional functions.
  // console.log("done!!")
  }
)
```

**Comment by SBoudrias** [comment]
Updated the readme accordingly.
