### ISSUE TITLE
Need help modifying lib

### ISSUE THREAD

**Issue by ORESoftware** [SBoudrias/Inquirer.js#453]
Looking to modify the lib so that the backspace key allows the user to return to the previous question.

```js

Prompt.prototype._run = function (cb) {
  this.done = cb;

  var self = this;

  var events = observe(this.rl, this);   // pass this to observe()
...etc

```

If I add this to `lib/utils/events`:

```js

module.exports = function (rl, self) {

  var keypress = rx.Observable.fromEvent(rl.input, 'keypress', normalizeKeypressEvents)
    .filter(function (e) {
      // Ignore `enter` key. On the readline, we only care about the `line` event.
      return e.key.name !== 'enter' && e.key.name !== 'return';
    });

  return {
    
    line: rx.Observable.fromEvent(rl, 'line'),

    keypress: keypress,

    normalizedBackspaceKey: keypress.filter(function (e) {
      if(e.key.name === 'backspace' || e.key.name === 'delete'){
        // if(self){
          self.backspaceHit = true;  << self is not defined in some cases
        // }

        return true;
      }
    }).share(),
```

I get this error:

```

 TypeError: Cannot set property 'backspaceHit' of undefined
    at /Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/lib/utils/events.js:24:29
    at /Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:5738:78
    at tryCatcher (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:5755:49)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:1762:31)
    at Subject.onNext (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:5998:19)
    at Subject.tryCatcher (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:63:31) 


```

I am super confused, at what point does the rx library call the Inquirer code in lib/utils/events?

As you can see:

  ```
  at /Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/lib/utils/events.js:24:29
    at /Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:5738:78
    at tryCatcher 
```

it appears that node_modules/rx/dist/rx.js is calling the code in lib/utils/events.js

Basically, what I am trying to do is

(1) Listen to backspace events
(2) if backspace event happens, flip a boolean, and then run rl.emit('line')
(3) Listeners should stop listening, but since the boolean is flipped we no longer submit the result

Please let me know if you have an idea as to how to help, thanks

**Comment by ORESoftware** [comment]
nevermind, I sort of figured it out
