### ISSUE TITLE
Error: This socket is closed

### ISSUE THREAD

**Issue by syuilo** [SBoudrias/Inquirer.js#458]
Code:
```js
const inquirer = require('inquirer');

inquirer.prompt([{
    type: 'input',
    name: 'name',
    message: 'your name:'
}]);
```

Got:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Domain.debugDomainError (repl.js:370:22)
    at emitOne (events.js:96:13)
    at Domain.emit (events.js:188:7)
    at Domain._errorHandler (domain.js:97:23)
    at process._fatalException (bootstrap_node.js:289:33)
    at Domain._errorHandler (domain.js:124:26)
    at process._fatalException (bootstrap_node.js:289:33)
```

Node: 7.1.0
OS: Windows 10

Thanks!

**Comment by SBoudrias** [comment]
Node 7.1.0 is broken https://github.com/nodejs/node/issues/9542

Only option is to use an older Node version (Node's bug fix is planned for release next Tuesday as either 7.1.1 or 7.2.0)
