### ISSUE TITLE
Error on Keypress of "<a>" or "<i>"

### ISSUE THREAD

**Issue by DerekTBrown** [SBoudrias/Inquirer.js#528]
When I press the "a" or "i" keys to select things in a checklist, I get the following error: 

```
ReferenceError: i is not defined
    at repl:1:1
    at sigintHandlersWrap (vm.js:94:15)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

**Comment by SBoudrias** [comment]
Hey @DerekTBrown, looks like you're running in a REPL interface. This means each time you type something and press enter, node will eval the line and try to run it as JavaScript code.

You won't be able to run any command line tools inside a REPL session.
