### ISSUE TITLE
Error using editor at Subscription.dispose

### ISSUE THREAD

**Issue by felixsanz** [SBoudrias/Inquirer.js#637]
When i use editor and save/exit, i get an exception: `Subscription.dispose is not a function`

Any idea why?

**Comment by RayBenefield** [comment]
Just wanted to echo that I just ran into this problem as well. Below is my stack trace in case it helps.

```
TypeError: this.lineSubscription.dispose is not a function
    at EditorPrompt.onEnd (/Users/RayBenefield/Development/kikd/node_modules/inquirer/lib/prompts/editor.js:86:27)
    at SafeSubscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/Observable.ts:256:13)
    at SafeSubscriber.__tryOrUnsub (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:255:10)
    at SafeSubscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:205:14)
    at Subscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:136:22)
    at Subscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:96:12)
    at TakeSubscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/operators/take.ts:80:24)
    at TakeSubscriber.Subscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:96:12)
    at FilterSubscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/operators/filter.ts:96:24)
    at FilterSubscriber.Subscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:96:12)
    at RefCountSubscriber.Subscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:136:22)
    at RefCountSubscriber.Subscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:96:12)
    at Subject.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subject.ts:61:17)
    at ConnectableSubscriber.Subscriber._next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:136:22)
    at ConnectableSubscriber.Subscriber.next (/Users/RayBenefield/Development/kikd/node_modules/src/Subscriber.ts:96:12)
    at MergeMapSubscriber.notifyNext (/Users/RayBenefield/Development/kikd/node_modules/src/operators/mergeMap.ts:154:24)

/Users/RayBenefield/Development/kikd/node_modules/rxjs/Subject.js:61
            throw new ObjectUnsubscribedError_1.ObjectUnsubscribedError();
            ^
ObjectUnsubscribedError: object unsubscribed
    at new ObjectUnsubscribedError (/Users/RayBenefield/Development/kikd/node_modules/src/util/ObjectUnsubscribedError.ts:12:22)
    at Subject.error (/Users/RayBenefield/Development/kikd/node_modules/src/Subject.ts:68:13)
    at EditorPrompt.endExternalEditor (/Users/RayBenefield/Development/kikd/node_modules/inquirer/lib/prompts/editor.js:78:25)
    at /Users/RayBenefield/Development/kikd/node_modules/external-editor/main/index.js:64:18
    at /Users/RayBenefield/Development/kikd/node_modules/external-editor/main/index.js:120:24
    at ChildProcess.<anonymous> (/Users/RayBenefield/Development/kikd/node_modules/external-editor/main/index.js:204:20)
    at ChildProcess.emit (events.js:159:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
```

**Comment by felixsanz** [comment]
Even the example from examples folders doesn't work. @SBoudrias do you have any idea on how to debug this further?

**Comment by user3587412** [comment]
In `editor.js`,

```diff
- 26 this.lineSubscription = events.line.forEach(this.startExternalEditor.bind(this));
+ 26 this.lineSubscription = events.line.subscribe(this.startExternalEditor.bind(this));
...
- 86 this.lineSubscription.dispose();
+ 86 this.lineSubscription.unsubscribe();
```

Should fix this specific problem for now. Before, `forEach` used to subscribe to an observable but now it returns a promise. I'll try to submit a patch soon

**Comment by felixsanz** [comment]
@user3587412  can we get a version bump please? this is a critical bug for those that use the editor prompt :disappointed:
