### ISSUE TITLE
TypeError when using editor

### ISSUE THREAD

**Issue by jonasstenberg** [SBoudrias/Inquirer.js#741]
Hi!

First off, thanks for an awesome project!

I'm trying to use the `editor` type, looking like this: 
```
const options = () => [{
  type: 'editor',
  name: 'text',
  message: 'Please write something',
}];

const answer = await inquirer.prompt(options);
```

But it throws an error: 
```
TypeError: obs.pipe is not a function
    at PromptUI.run (/.../node_modules/inquirer/lib/ui/prompt.js:33:24)
    at Object.promptModule [as prompt] (/.../node_modules/inquirer/lib/inquirer.js:28:22)
    at chooseReleaseNotes (/.../lib/inquiry/release.js:24:37)
    at makeInquiry (/.../lib/inquiry/index.js:70:25)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

I'm using `neovim`, but I've tried to switch to `vim` just for debugging, but I still get the same error.
Using version 6.0.0.
Any clues to why?

Thanks!

**Comment by SinanAkkoyun** [comment]
Same for me, please help...

**Comment by SBoudrias** [comment]
Try `inquirer@10` or start using our new API `@inquirer/prompts`. Both of those now have built-in types instead of relying on external types.
