### ISSUE TITLE
prompt.onCompletion() fails during cancel input process with vorpal.cancel

### ISSUE THREAD

**Issue by h-philipp** [SBoudrias/Inquirer.js#823]
Fail in prompt.ui and base.ui when cancel input process with vorpal.cancel(function () {
            vorpal.log('Aborting... ');
            return false;
        })

prompt.onCompletetion() will call this.close() which then wants to remove a listener which is not available anymore (maybe with forceClose already removed):

close() {
    // Remove events listeners
this.rl.removeListener('SIGINT', this.onForceClose);

TypeError: Cannot read property 'removeListener' of null
    at module.exports.UI.close (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\vorpal\node_modules\inquirer\lib\ui\baseUI.js:45:11)
    at module.exports.PromptUI.onCompletion (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\vorpal\node_modules\inquirer\lib\ui\prompt.js:54:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:1489:14)
    at Subject.onCompleted (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:5871:19)
    at Subject.tryCatcher (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:1489:14)
    at AutoDetachObserver.tryCatcher (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\phal\workspace\amv-autologg-support-commander\node_modules\rx-lite\rx.lite.js:5796:56)

**Comment by SBoudrias** [comment]
Closing this ticket as stale. Open new issues if you encounter problem with the [new Inquirer API](https://github.com/SBoudrias/Inquirer.js/issues/293#1214).
